routes/web.php
<?php
Route::group(['middleware' => 'statistic'], function(){

    Route::resource('users', 'MainPageController', ['users'])->only(['index','show']);
    Route::resource('articles', 'ArticleController', ['articles'])->only(['index', 'show']);
    Route::resource('jobs', 'JobController', ['jobs'])->only(['index']);

    Route::resource('statistics', 'StatisticController', ['statistics'])->only(['index']);

    Route::group(['middleware' => 'auth'], function(){
        Route::resource('articles', 'ArticleController', ['articles'])->only(['create', 'store', 'edit', 'update', 'destroy']);
        Route::resource('users', 'MainPageController', ['users'])->only(['edit','update','destroy'])->middleware('self');
        Route::resource('words', 'WordController', ['words'])->only(['index']);
        Route::resource('films', 'FilmController', ['films']);
        Route::post('/mark_word/{word}', 'WordController@learn');
        Route::post('/translate_word/{word}', 'WordController@correctionTranslate');
        Route::post('/update_word/{word}', 'WordController@update');
        Route::post('/delete_word/{word}', 'WordController@destroy');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    });

    Route::get('/', function (){
        return redirect()->route('users.index');
    });
    Auth::routes();
});

app/Models/User.php
<?php

namespace App;

use App\Traits\Searchable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name','middle_name','last_name', 'email','skype','linkedin','cv', 'image', 'password',
    ];

    /**
     * Массив полей для поиска (Searchable)
     *
     * @var array
     */
    protected $searchable = ['first_name', 'last_name', 'middle_name'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function projects()
    {
        return $this->hasMany(Project::class);
    }
    public function skills()
    {
        return $this->belongsToMany(Skill::class, 'user_skill', 'user_id', 'skill_id');
    }
    public function educations()
    {
        return $this->hasMany(Education::class);
    }

    public function scopePepe($query)
    {
        return $query->where('rating', 0);
    }
}

resources/views/users/users_edit.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')

    <div class="container">
        <div class="row my-4">
            <div class="col">
                <h3>
                    Редактирование
                </h3>
            </div>
        </div>
        <div class="row">
            <div class="col">
                @if(count($errors->all()) > 0)
                    <div class="row">
                        <div class="col">
                            <div class="alert alert-danger" role="alert">
                                {{ $errors->first() }}
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="post" action="{{route('users.update', ['user' => $user->id])}}" enctype="multipart/form-data" novalidate class="needs-validation">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="last_name">Фамилия</label>
                        <input type="text" class="form-control" id="last_name" name="last_name" value="{{$user->last_name}}"
                               required pattern="[A-Za-zА-Яа-яЁё\s\-]{1,255}">
                    </div>
                    <div class="form-group">
                        <label for="first_name">Имя</label>
                        <input type="text" class="form-control" id="first_name" name="first_name"
                               value="{{$user->first_name}}" required pattern="[A-Za-zА-Яа-яЁё\s\-]{1,255}">
                    </div>
                    <div class="form-group">
                        <label for="middle_name">Отчество</label>
                        <input type="text" class="form-control" id="middle_name" name="middle_name" value="{{$user->middle_name}}"
                               required pattern="[A-Za-zА-Яа-яЁё\s\-]{1,255}">
                    </div>
                    <div class="form-group">
                        <label for="email">Почта</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{$user->email}}"
                               required>
                    </div>
                    <div class="form-group">
                        <label for="skype">Skype</label>
                        <input type="text" class="form-control" id="skype" name="skype" value="{{$user->skype}}"
                               required pattern=".{1,255}">
                    </div>

                    <div class="form-group">
                        <label for="linkedin">Linkedin</label>
                        <input type="url" class="form-control" id="linkedin" name="linkedin" value="{{$user->linkedin}}"
                               required pattern="http(s)?://.*">
                    </div>
                    <div class="form-group">
                        <label for="cv">Резюме</label>
                        <input type="url" class="form-control" id="cv" name="cv" value="{{$user->cv}}"
                               required pattern="http(s)?://.*">
                    </div>
                    <div class="form-group">
                        <label for="image">Изображение</label>
                        <input type="file" class="form-control" id="image" name="image" value="{{$user->image}}">
                        @isset($user->image)
                            {{'Текущее изображение - '.$user->image}}
                        @endisset
                    </div>

                    <div class="form-group">
                        <label for="skills">Навыки</label>
                        <select multiple class="form-control" name="skills[]" id="skills">
                            <option value="" disabled>Выберите навыки</option>
                            @foreach($skills as $key => $skill)
                                <option value="{{$key}}" {{$user->skills->contains($key) ? 'selected="selected"' : ''}}>{{$skill}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group projects">
                        <label>Проекты</label>
                        @foreach($user->projects as $project)
                            <div class="row">
                               @component('users.components.project_item', ['project' => $project])@endcomponent
                            </div>
                        @endforeach
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-success mb-2" id="create-project">Добавить проект</button>
                    </div>
                    <div class="form-group educations">
                        <label>Учебные заведения</label>
                        @foreach($user->educations as $education)
                            <div class="row">
                               @component('users.components.education_item', ['education' => $education])@endcomponent
                            </div>
                        @endforeach
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-success mb-2" id="create-education">Добавить учебное заведение</button>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success mb-2">Сохранить текущие изменения</button>
                        <a href="{{route('users.show', ['user' => auth()->id()])}}" type="button" class="btn btn-secondary mb-2">Назад</a>
                    </div>
                </form>
                <br><br>
                <form action="{{route('users.destroy', ['user' => $user->id])}}" method="POST" style="display: inline-block;">
                    @method('delete')
                    @csrf
                    <button type="submit" class="btn btn-danger mb-2">Удалить профиль</button>
                </form>
            </div>
        </div>
    </div>
    <template id="project-template">
        <div class="row">
            @component('users.components.project_item', ['project' => new stdClass()])@endcomponent
        </div>
    </template>
    <template id="education-template">
        <div class="row">
            @component('users.components.education_item', ['education' => new stdClass()])@endcomponent
        </div>
    </template>
@endsection

@push('scripts')
    <script>
        var counter = -2;

        document.getElementById('create-project').onclick = function (e) {
            var template = document.getElementById('project-template');
            var inputs = template.content.querySelectorAll('input, textarea');
            for(var i = 0; i < inputs.length; i++){
                inputs[i].name = inputs[i].name.replace( counter + 1, counter);
            }
            var project =  document.importNode(template.content, true);
            document.querySelector('div.projects').append(project);
            counter--;
        };

        document.getElementsByClassName('projects')[0].onclick = function (e) {
            var target = e.target;
            if(target.classList.contains('delete-project')){
                target.closest('div.row').remove();
            }
        } ;
        document.getElementById('create-education').onclick = function (e) {
            var template = document.getElementById('education-template');
            var inputs = template.content.querySelectorAll('input, textarea');
            for(var i = 0; i < inputs.length; i++){
                inputs[i].name = inputs[i].name.replace( counter + 1, counter);
            }
            var education =  document.importNode(template.content, true);
            document.querySelector('div.educations').append(education);
            counter--;
        };

        document.getElementsByClassName('educations')[0].onclick = function (e) {
            var target = e.target;
            if(target.classList.contains('delete-education')){
                target.closest('div.row').remove();
            }
        }
    </script>
@endpush

resources/views/users/users_show.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <!--HOME-->
    <section id="home">
        <div class="container">
            <div class="row">
                <div class="col-12 wrap-hero-content">
                    <div class="hero-content">
                        <h1>Дароу</h1>
                        <br>
                        <span class="typed">"._."</span>
                    </div>
                </div>
                <div class="col-12 mouse-icon">
                    <div class="scroll"></div>
                </div>
            </div>
        </div>
    </section>
    <!--/.HOME END-->

    <!--ABOUT-->
    <section id="about">
        <div class="row">
            <div class="col-md-6 no-gutters no-pad">
                <div class="bg-about" @if($user->image)style="background-image: url('{{asset('storage/users/'.$user->id.'/'.$user->image)}}')"@endif></div>
            </div>
            <div class="col-md-6 no-gutters no-pad">
                <div class="row">
                <div class="col-12 white-col">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12">
                            <div class="wrap-about">
                                <table class="w-content">
                                    <tr>
                                        <td class="title">Фамилия</td>
                                        <td class="break">:</td>
                                        <td>{{$user->last_name}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title">Имя</td>
                                        <td class="break">:</td>
                                        <td>{{$user->first_name}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title">Отчество</td>
                                        <td class="break">:</td>
                                        <td>{{$user->middle_name}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title">Email</td>
                                        <td class="break">:</td>
                                        <td>{{$user->email}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title">Skype</td>
                                        <td class="break">:</td>
                                        <td>{{$user->skype}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title">LinkedIn</td>
                                        <td class="break">:</td>
                                        <td>
                                            <a href="{{$user->linkedin}}">
                                                {{"{$user->last_name} {$user->first_name}"}}
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title">Резюме</td>
                                        <td class="break">:</td>
                                        <td>
                                            <a href="{{$user->cv}}">
                                                {{"{$user->last_name} {$user->first_name}"}}
                                            </a>
                                        </td>
                                    </tr>
                                    @if(auth()->user() && (auth()->id() == $user->id))
                                        <tr>
                                            <td colspan="3">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3">
                                                <a href="{{route('users.edit', ['user' => auth()->id()])}}" class="btn btn-secondary">
                                                    Редактирование
                                                </a>
                                            </td>
                                        </tr>
                                    @endif
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </section>
    <!--/.ABOUT END-->

    <!--WORK-->
    @if($user->projects->count() > 0)
    <section class="grey-bg mar-tm-10" id="work">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h3 class="title-small">
                        <span>Проекты</span>
                    </h3>
                    <hr>
                    <p class="content-detail">
                        Проекты в которых я принимал участие.
                    </p>
                </div>
                <div class="col-md-9 content-right">
                    <div class="row">
                        @foreach($user->projects as $project)
                            <div class="col-md-6">
                                <div class="card border-secondary mb-3">
                                    <div class="card-header">
                                        <h5 class="card-title">
                                            <a href="{{$project->link}}">
                                                {{$project->name}}
                                            </a>
                                        </h5>
                                    </div>
                                    <div class="card-body">
                                        <p class="card-text">
                                            {{$project->desc}}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>
    @endif

    <!--EDUCATION-->
    @if($user->educations->count() > 0)
    <section class="white-bg" id="education">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h3 class="title-small">
                        <span>Образование</span>
                    </h3>
                    <hr>
                    <p class="content-detail">
                        Оконченные учебные заведения.
                    </p>
                </div>
                <div class="col-md-9 content-right">
                    <div class="row">
                        @foreach($user->educations as $education)
                            <div class="col-md-6 col-sm-6">
                                <div class="card border-secondary mb-3">
                                    <div class="card-header">
                                        <h5 class="card-title">
                                            {{$education->institute}}
                                        </h5>
                                    </div>
                                    <div class="card-body">
                                        <h6 class="card-subtitle mb-2 text-muted">{{$education->name}}</h6>
                                        <p class="card-text">
                                            {{$education->desc}}
                                            <br>
                                            {{"{$education->startY} - {$education->endY}"}}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>
    @endif
    <!--/.EDUCATION END-->

    {{--<!--CONTACT-->--}}
    {{--<section id="contact" class="grey-bg">--}}
        {{--<div class="container">--}}
            {{--<div class="row">--}}
                {{--<div class="col-md-3">--}}
                    {{--<h3 class="title-small">--}}
                        {{--<span>Контакты</span>--}}
                    {{--</h3>--}}
                    {{--<p class="content-detail">--}}
                        {{--Свяжитесь со мной.--}}
                    {{--</p>--}}
                {{--</div>--}}
                {{--<div class="col-md-9 content-right">--}}
                    {{--<form>--}}
                        {{--<div class="group">--}}
                            {{--<input required="" type="text"><span class="highlight"></span><span--}}
                                    {{--class="bar"></span><label>Имя</label>--}}
                        {{--</div>--}}
                        {{--<div class="group">--}}
                            {{--<input required="" type="email"><span class="highlight"></span><span class="bar"></span><label>Email</label>--}}
                        {{--</div>--}}
                        {{--<div class="group">--}}
                            {{--<textarea required=""></textarea><span class="highlight"></span><span--}}
                                    {{--class="bar"></span><label>Сообщение</label>--}}
                        {{--</div>--}}
                        {{--<input id="sendMessage" name="sendMessage" type="submit" value="Отправить сообщение">--}}
                    {{--</form>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</section>--}}
    {{--<!--/.CONTACT END-->--}}
@endsection