routes/web.php
<?php
Route::group(['middleware' => 'statistic'], function(){

    Route::resource('users', 'MainPageController', ['users'])->only(['index','show']);
    Route::resource('articles', 'ArticleController', ['articles'])->only(['index', 'show']);
    Route::resource('jobs', 'JobController', ['jobs'])->only(['index']);

    Route::resource('statistics', 'StatisticController', ['statistics'])->only(['index']);

    Route::group(['middleware' => 'auth'], function(){
        Route::resource('articles', 'ArticleController', ['articles'])->only(['create', 'store', 'edit', 'update', 'destroy']);
        Route::resource('users', 'MainPageController', ['users'])->only(['edit','update','destroy'])->middleware('self');
        Route::resource('words', 'WordController', ['words'])->only(['index']);
        Route::resource('films', 'FilmController', ['films']);
        Route::post('/mark_word/{word}', 'WordController@learn');
        Route::post('/translate_word/{word}', 'WordController@correctionTranslate');
        Route::post('/update_word/{word}', 'WordController@update');
        Route::post('/delete_word/{word}', 'WordController@destroy');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    });

    Route::get('/', function (){
        return redirect()->route('users.index');
    });
    Auth::routes();
});

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    protected $table = 'films';

    protected $fillable = ['title', 'file'];

    public function words()
    {
        return $this->belongsToMany(Word::class, 'film_word', 'film_id', 'word_id');
    }
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\CreateFilmDictionary;
use App\Models\Film;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $films = Film::pluck('title', 'id');

        return view('films.index', compact('films'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('films.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $path = $request->file('file')->store('films');
        $title = $request->title;

        $film = Film::create([
            'title' => $title,
            'file' => $path
        ]);

        CreateFilmDictionary::dispatch($film);

        return redirect()->route('films.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Request $request
     * @param  Film $film
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Film $film)
    {
        $statuses = array_values($request->input('statuses', []));

        $film = $film->load(['words' => function ($q) use ($statuses) {
            $q->when(count($statuses) > 0, function ($i) use ($statuses) {
                return $i->whereIn('status', $statuses)->orderBy('status', 'desc');
            }, function ($i) {
                return $i->where('status', '>', 9)->orderBy('status', 'desc');
            });

        }]);
        return view('films.show', compact('film', 'statuses'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Film $film
     * @return \Illuminate\Http\Response
     */
    public function destroy(Film $film)
    {
        $film->delete();
        return redirect()->route('films.index');
    }
}

resources/views/films/create.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <section>
        <div class="container">
            <div class="row my-4">
                <div class="col">
                    <h1>Создание фильма</h1>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <form action="{{route('films.store')}}" method="POST" class="needs-validation" novalidate enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="name">Название фильма</label>
                            <input type="text" class="form-control" id="title" name="title" required pattern=".{1,255}"
                                   placeholder="Введите название">
                        </div>
                        <div class="form-group">
                            <label for="file">Контентная часть заметки</label>
                            <input type="file" class="form-control" id="file" name="file" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success mb-2">Создать</button>
                            <a href="{{route('films.index')}}" type="button" class="btn btn-secondary mb-2">Назад</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/films/index.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <section>
        <div class="container">
            <div class="row my-4">
                <div class="col">
                    <h1>Фильмы</h1>
                    @csrf
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <a href="{{route('films.create')}}" type="button" class="btn btn-dark mb-2">Создать</a>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <div class="table-responsive">
                        <table class="words table table-striped hide_answer">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Фильм</th>
                                <th>Перейти к словарю</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($films as $key => $item)
                                <tr class="word-row">
                                    <td>{{$key}}</td>
                                    <td class="film">{{$item}}</td>
                                    <td>
                                        <a href="{{route('films.show', $key)}}" type="button" class="btn btn-dark mark_word">>
                                        </a>
                                    </td>
                                    <td>
                                        <form action="{{route('films.destroy', ['film' => $key])}}"
                                              method="POST">
                                            @method('delete')
                                            @csrf
                                            <button type="submit" class="close" title="Удалить?">
                                                <span style="color: #ff362e;" aria-hidden="true">&times;</span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {{--<script>--}}
        {{--document.querySelector('tbody').onclick = function (e) {--}}
            {{--let button = e.target;--}}
            {{--if (button.classList.contains("mark_word")) {--}}
                {{--$.ajax({--}}
                    {{--type: "POST",--}}
                    {{--url: '/mark_word/' + button.getAttribute('data-id'),--}}
                    {{--data: {},--}}
                    {{--headers: {--}}
                        {{--'X-CSRF-Token': document.getElementsByName('_token')[0].value--}}
                    {{--},--}}
                    {{--success: function (res) {--}}
                        {{--button.closest('tr').remove();--}}
                    {{--},--}}
                    {{--error: function (error) {--}}
                        {{--alert('Что-то пошло не так.');--}}
                    {{--}--}}
                {{--});--}}
            {{--}--}}

        {{--};--}}
        {{--document.getElementById('show_translate').onclick = (e) => {--}}
            {{--document.querySelector('.words').classList.toggle('hide_answer');--}}
        {{--}--}}
    {{--</script>--}}
@endsection

resources/views/films/show.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <section>
        <div class="container">
            <div class="row my-4">
                <div class="col">
                    <h1>Фильм - {{$film->title . '(' . $film->words->count() .')'}}</h1>
                    @csrf
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <form action="{{route('films.show', ['film' => $film->id])}}" method="GET">
                        @foreach(range(0,9) as $item)
                            <div class="form-group form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" name="statuses[]" value="{{$item}}"
                                           @if(in_array($item, $statuses))checked="checked"@endif>
                                    {{$item}}
                                </label>
                            </div>
                        @endforeach
                        <button type="submit" class="btn btn-primary pull-right">Submit</button>
                    </form>
                </div>
                <div class="col-md-2">
                    <button type="button" class="btn btn-dark pull-right" id="show_translate">Показать</button>
                </div>
            </div>
        </div>
        <div class="container no-pad">
            @component('components.words.words_table', ['words' => $film->words])@endcomponent
        </div>
    </section>
    <script>
        document.getElementById('show_translate').onclick = (e) => {
            document.querySelector('.words').classList.toggle('hide_answer');
        }
    </script>
@endsection
@stack('words_table_row_scripts')