routes/web.php
<?php
Route::group(['middleware' => 'statistic'], function(){

    Route::resource('users', 'MainPageController', ['users'])->only(['index','show']);
    Route::resource('articles', 'ArticleController', ['articles'])->only(['index', 'show']);
    Route::resource('jobs', 'JobController', ['jobs'])->only(['index']);

    Route::resource('statistics', 'StatisticController', ['statistics'])->only(['index']);

    Route::group(['middleware' => 'auth'], function(){
        Route::resource('articles', 'ArticleController', ['articles'])->only(['create', 'store', 'edit', 'update', 'destroy']);
        Route::resource('users', 'MainPageController', ['users'])->only(['edit','update','destroy'])->middleware('self');
        Route::resource('words', 'WordController', ['words'])->only(['index']);
        Route::resource('films', 'FilmController', ['films']);
        Route::post('/mark_word/{word}', 'WordController@learn');
        Route::post('/translate_word/{word}', 'WordController@correctionTranslate');
        Route::post('/update_word/{word}', 'WordController@update');
        Route::post('/delete_word/{word}', 'WordController@destroy');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    });

    Route::get('/', function (){
        return redirect()->route('users.index');
    });
    Auth::routes();
});

app/Models/Article.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = ['content', 'user_id', 'name'];



    /**
     * @return string
     */
    public function getDateAttribute()
    {
        return Carbon::parse($this->created_at)->format('d.m.Y');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $options = $this->checkOptions($request->all());
        $articles = Article::whereDate('created_at', '>=', $options['start_date'])
            ->whereDate('created_at', '<=', $options['end_date'])
            ->orderBy('created_at', $options['sort'])
            ->get();

        return view('articles.articles_list', compact('articles', 'options'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.articles_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ArticleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $data = $request->all();
        $data['user_id'] = auth()->id();
        Article::create($data);
        return redirect()->route('articles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view('articles.articles_show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('articles.articles_edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ArticleRequest   $request
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, Article $article)
    {
        $data = $request->all();
        $article->update($data);
        return redirect()->route('articles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('articles.index');
    }

    /**
     * Изменение настроек для фильтрации
     *
     * @param array $data
     * @return array
     */
    protected function checkOptions(array $data = [])
    {
        /**
         * Проверка опций из реквеста, задание значений по умолчанию (для исключения ошибок ввода)
         * todo: потом переделать под ajax
         */
        return [
            'start_date' => ($x = \DateTime::createFromFormat('Y-m-d', ($data['start_date'] ?? ''))) ? $x->format('Y-m-d')
                : (date('Y-m-d', time() - (25 * 24 * 60 * 60))),
            'end_date' => ($y = \DateTime::createFromFormat('Y-m-d', ($data['end_date'] ?? ''))) ? $y->format('Y-m-d')
                : (date('Y-m-d')),
            'sort' => ($data['sort'] ?? '') == 'asc' ? 'asc' : 'desc',
        ];
    }
}

resources/views/articles/articles_create.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <div class="container">
        <div class="row my-4">
            <div class="col">
                <h1>Создание заметки</h1>
            </div>
        </div>
        @if(count($errors->all()) > 0)
            <div class="row">
                <div class="col">
                    <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                    </div>
                </div>
            </div>
        @endif
        <div class="row mb-4">
            <div class="col">
                <form action="{{route('articles.store')}}" method="POST" class="needs-validation" novalidate>
                    @csrf
                    <div class="form-group">
                        <label for="name">Название заметки</label>
                        <input type="text" class="form-control" id="name" name="name" required pattern=".{1,255}"
                               placeholder="Введите название">
                    </div>
                    <div class="form-group">
                        <label for="content">Контентная часть заметки</label>
                        <textarea class="form-control" id="content" name="content" rows="5" cols="10" required maxlength="9999"
                                  placeholder="Содержимое заметки..."></textarea>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success mb-2">Создать</button>
                        <a href="{{route('articles.index')}}" type="button" class="btn btn-secondary mb-2">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/articles/articles_edit.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <div class="container">
        <div class="row my-4">
            <div class="col">
                <h1>Редактирование заметки</h1>
            </div>
        </div>
        @if(count($errors->all()) > 0)
            <div class="row">
                <div class="col">
                    <div class="alert alert-danger" role="alert">
                        {{ $errors->first() }}
                    </div>
                </div>
            </div>
        @endif
        <div class="row mb-4">
            <div class="col">
                <form action="{{route('articles.update', ['article' => $article->id])}}" method="POST" novalidate class="needs-validation">
                    @method('put')
                    @csrf
                    <div class="form-group">
                        <label for="name">Название заметки</label>
                        <input required pattern=".{1,255}" type="text" class="form-control" id="name" name="name" value="{{$article->name}}">
                    </div>
                    <div class="form-group">
                        <label for="content">Контентная часть</label>
                        <textarea required maxlength="9999" class="form-control" id="content" name="content">{{ $article->content }}</textarea>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success mb-2">Сохранить</button>
                        <a href="{{route('articles.index')}}" type="button" class="btn btn-secondary mb-2">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/articles_list.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <div class="container">
        <div class="row my-4">
            <div class="col">
                <h1>Заметки</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form action="{{route('articles.index')}}" method="GET">
                    <div class="form-row">
                        <div class="col-12 mb-2">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="start_date">От</label>
                                        <input type="date" class="form-control" id="start_date" name="start_date"
                                               value="{{$options['start_date']}}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="end_date">До</label>
                                        <input type="date" class="form-control" id="end_date" name="end_date" value="{{$options['end_date']}}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label >Сортировка</label><br>
                                        <input type="radio" style="display: none;" id="asc" name="sort" value="asc"
                                               @if($options['sort'] == 'asc')checked="checked"@endif title="Начиная с поздних">
                                        <input type="radio" style="display: none;" id="desc" name="sort" value="desc"
                                               @if($options['sort'] == 'desc')checked="checked"@endif title="Начиная с ранних">
                                        <label for="asc" class="sorting-label-asc"><i class="fa fa-sort-amount-asc" aria-hidden="true"></i></label>
                                        <label for="desc" class="sorting-label-desc"><i class="fa fa-sort-amount-desc" aria-hidden="true"></i></label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-success mb-2">Применить фильтр</button>
                                    @auth()
                                        <a href="{{route('articles.create')}}" type="button" class="btn btn-secondary mb-2">Создать заметку</a>
                                    @endauth
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
    </div>
    <div class="container">
        @if($articles->count() > 0)
            <div class="row">
                @foreach($articles as $article)
                    <div class="col-md-6 col-lg-4">
                        <div class="card border-secondary mb-3">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-10">
                                        <a href="{{route('articles.show', ['article' => $article->id])}}">
                                            <h5 class="card-title">{{$article->name}}</h5>
                                        </a>
                                        <span class="card-subtitle mb-2 text-muted">{{$article->date}}</span>
                                    </div>
                                    <div class="col-2">
                                        <form action="{{route('articles.destroy', ['article' => $article->id])}}"
                                              method="POST">
                                            @method('delete')
                                            @csrf
                                            <button type="submit" class="close" title="Удалить?">
                                                <span style="color: #ff362e;" aria-hidden="true">&times;</span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body text-secondary">
                                <p class="card-text">{{$article->content}}</p>
                                <hr>
                                <a href="{{route('articles.edit', ['article' => $article->id])}}" class="btn btn-secondary">Редактировать</a>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        @else
            <div class="row">
                <div class="col">
                    <p>Нет заметок ...</p>
                </div>
            </div>
        @endif
        <br><br>
    </div>
@endsection

resources/views/articles/articles_show.blade.php
@extends('layouts.main_layout')

@section('menu')
    @include('menu.main_menu')
@endsection

@section('content')
    <div class="container">
        <div class="row my-4">
            <div class="col">
                <h1>Просмотр</h1>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">{{$article->name}}</h5>
                        <span class="card-subtitle mb-2 text-muted">{{$article->date}}</span>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{$article->content}}</p>
                        <hr>
                        <a href="{{route('articles.index')}}" type="button" class="btn btn-secondary mb-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection